### ISSUE TITLE
@google-cloud/pubsub should be a peer dependency

### ISSUE THREAD

**Issue by caseyduquettesc** [ert78gb/google-pubsub-emulator#7]
Listing pubsub as a dependency locks the dependent project to that version unless they want multiple versions installed which doesn't end well since google relies heavily on grpc

**Comment by caseyduquettesc** [comment]
If you look at https://nodesource.com/blog/semver-tilde-and-caret/,

> Using the caret for versions less than 0.1.0 offers no flexibility at all. Only the exact version specified will be valid.
> For example, ^0.0.3 will only permit only exactly version 0.0.3.

Listing ^0.7 as a dependency forces all users to include pubsub 0.7, and is now incompatible if you also have pubsub 0.14.4

**Comment by ert78gb** [comment]
I published a new release with 2.0.0
